### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/nbgitpuller-link-generator-webextension#1]
This repo is a fork of https://github.com/yuvipanda/nbgitpuller-link-generator-webextension.

Upstream's released extension broke when GitHub changed the UI. @ranashreyas submitted a PR to fix this, but @yuvipanda is extremely busy and doesn't have time for frequent code reviews. We also do not have dedicated staff to do proper code reviews. Normally we'd have no trouble temporarily relying on software sourced from a git branch, however the Chrome Web Store can only deploy an official release. After discussion with Yuvi, we've decided to temporarily fork the extension and make a distinctly named release to the Chrome Web Store. If/when upstream is able to merge our changes, we can sunset this one.

The current extension is called "nbgitpuller Link generator" in the web store, https://chromewebstore.google.com/search/nbgitpuller. Yuvi suggested Berkeley branding, however I'm somewhat hesitant to go in that direction because I suspect it would involve an extensive formal process. We might consider something like "JupyterHub Link Generator"  or "DataHub Link Generator". The former is appropriate because anyone can use this extension with their hub, but it may signal that this fork has a more formal relationship with JupyterHub than it actually does. The DataHub name variant is Berkeley-adjacent, but Using "DataHub" in the name feels like it could dissuade other people from using it. I'm more in favor of "JupyterHub Link Generator" right now.

Upstream's web store URL is https://chromewebstore.google.com/detail/nbgitpuller-link-generato/hpdbdpklpmppnoibabdkkhnfhkkehgnc. I'm not sure how it was assigned "nbgitpuller-link-generato" (missing r) in the URL, but I suspect that the full term was based on the name. I'd go with "jupyterhub-link-generator" if asked.

We should clearly mention in the Chrome Web Store that this is a fork of upstream, with a small number of modifications. We should indicate that people should use upstream and send fixes upstream, unless our changes happen to solve a need for them.

Lastly, we should create a unique button icon. I don't think it should use formal Berkeley branding.

I don't think this fork's repo ("nbgitpuller-link-generator-webextension") needs to go under a different name right now.

## Tasks to be done

- [x] Pick a new name
- [x] Update README
- [x] Create a new icon
- [x] Craft a description for the Chrome Web Store, describing the differences
- [x] Publish extension

Thoughts?

**Comment by yuvipanda** [comment]
> The DataHub name variant is Berkeley-adjacent, but Using "DataHub" in the name feels like it could dissuade other people from using it. 

I actually think this is a feature, not a bug. I think making this more generic than UC Berkeley's datahub is going to cause confusion with the 'official' version. I think it should be clearly mentions this is specifically for use by UC Berkeley. 

My suggestion is 'UCB DataHub nbgitpuller generator extension'. I would strongly recommend against 'JupyterHub Link Generator'.

**Comment by balajialg** [comment]
@ryanlovett This is great. I worry about a formal relationship with upstream if we go with "Jupyterhub-link-generator" name. Let's go with the "Datahub Link generator" name instead. As you said, we should highlight that folks should use the upstream repo unless they need our changes to solve their need. 

@ranashreyas Can you please create a new PR to this repository and tag @ryanlovett and myself for code reviews?

**Comment by yuvipanda** [comment]
Also, it was @pamelafox who fixed the brokenness (https://github.com/yuvipanda/nbgitpuller-link-generator-webextension/pull/5 and https://github.com/yuvipanda/nbgitpuller-link-generator-webextension/pull/6).

**Comment by ryanlovett** [comment]
Okay, I'm an easy sell on the DataHub name variant.

I think @pamelafox's PR hadn't yet been merged prior to @ranashreyas's hiring/development efforts ? @balajialg knows more though.

**Comment by balajialg** [comment]
So, @ranashreyas started working on his changes which fixed the Github version of this plugin around the same time or even before @pamelafox made their changes to this repo - https://github.com/yuvipanda/nbgitpuller-link-generator-webextension. However, He did not commit his changes formally as a PR. Once Pamela's PR was merged, @ranashreyas dropped his earlier changes and made UI enhancements to the extension on top of the changes merged to the repository.
